from .Image_Paste_By_Bbox import NODE_CLASS_MAPPINGS as IMAGE_PASTE_BBOX_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PASTE_BBOX_DISPLAY_MAPPINGS
from .crop_by_mask import NODE_CLASS_MAPPINGS as CROP_MASK_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_MASK_DISPLAY_MAPPINGS
from .Image_Paste import NODE_CLASS_MAPPINGS as IMAGE_PASTE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_PASTE_DISPLAY_MAPPINGS
from .Image_To_Gray import NODE_CLASS_MAPPINGS as IMAGE_GRAY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_GRAY_DISPLAY_MAPPINGS
from .Image_Alpha_Blend_By_Bbox import NODE_CLASS_MAPPINGS as IMAGE_ALPHA_BLEND_BBOX_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_ALPHA_BLEND_BBOX_DISPLAY_MAPPINGS
from .Image_Alpha_Blend import NODE_CLASS_MAPPINGS as IMAGE_ALPHA_BLEND_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_ALPHA_BLEND_DISPLAY_MAPPINGS
from .Image_Gaussian_Blur import NODE_CLASS_MAPPINGS as IMAGE_GAUSSIAN_BLUR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_GAUSSIAN_BLUR_DISPLAY_MAPPINGS
from .Image_Remove_Alpha import NODE_CLASS_MAPPINGS as IMAGE_REMOVE_ALPHA_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_REMOVE_ALPHA_DISPLAY_MAPPINGS

# 合并节点映射
NODE_CLASS_MAPPINGS = {
    **IMAGE_PASTE_BBOX_MAPPINGS,
    **CROP_MASK_MAPPINGS,
    **IMAGE_PASTE_MAPPINGS,
    **IMAGE_GRAY_MAPPINGS,
    **IMAGE_ALPHA_BLEND_BBOX_MAPPINGS,
    **IMAGE_ALPHA_BLEND_MAPPINGS,
    **IMAGE_GAUSSIAN_BLUR_MAPPINGS,
    **IMAGE_REMOVE_ALPHA_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_PASTE_BBOX_DISPLAY_MAPPINGS,
    **CROP_MASK_DISPLAY_MAPPINGS,
    **IMAGE_PASTE_DISPLAY_MAPPINGS,
    **IMAGE_GRAY_DISPLAY_MAPPINGS,
    **IMAGE_ALPHA_BLEND_BBOX_DISPLAY_MAPPINGS,
    **IMAGE_ALPHA_BLEND_DISPLAY_MAPPINGS,
    **IMAGE_GAUSSIAN_BLUR_DISPLAY_MAPPINGS,
    **IMAGE_REMOVE_ALPHA_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS'] 